spring:
  application:
    name: pharma_connect_payment
  datasource:
    url: jdbc:postgresql://192.168.1.8:5432/payment
    password: password
    username: admin
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

#API_Key:api_T3sOGKfkxKa6SCAgFlR9vWNf4kVKWMTv4RvopHjOXMqeNRWghDL6iNmQk1nkqjKY
#SECRET_Key=secret_4b3e62f664f6a103309be1ffa7e6269f9e672195a3dca04d5c8295e2d905a880
#logging.level.org.springframework.web=DEBUG
server:
  port: 8060

application:
  jwt:
    secret: PxgfrbwwEfYXAf26-tZxhbXfez0ycDWhkPuOdmYGTqU
    server:
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFybWFDb25uZWN0Iiwic3ViIjoiXCJzdG9jay1zZXJ2aWNlXCIiLCJyb2xlIjoiU0VSVklDRSIsImlhdCI6MTcxNTI2Nzg5Nn0.KiQcFHAmucMY_NUEOtsoaZHCjrdzgHhG1rcIr_fktvI



